<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

class InsertItemsData extends Migration
{
    public function up()
    {
        DB::table('items')->insert([
            [
                'id' => 1,
                'active' => 1,
                'name' => 'Banner 01',
                'image' => '[{"file":"item-1_banner-01_1430344770.jpg","size":15007}]',
                'type' => 'banners',
                'categories' => null,
                'order' => 999,
                'place' => 1,
                'price' => 0.00,
                'date' => null,
                'created_at' => null,
                'updated_at' => '2025-07-14 01:59:55',
                'link' => null,
                'icon' => null,
            ],
            [
                'id' => 2,
                'active' => 0,
                'name' => 'Banner 02',
                'image' => '[{"file":"item-2_banner-02_36538987.jpg","size":15007}]',
                'type' => 'banners',
                'categories' => null,
                'order' => 999,
                'place' => 1,
                'price' => 0.00,
                'date' => null,
                'created_at' => null,
                'updated_at' => '2025-05-16 11:53:02',
                'link' => null,
                'icon' => null,
            ],
            [
                'id' => 33,
                'active' => 1,
                'name' => 'Behance',
                'image' => null,
                'type' => 'social_network',
                'categories' => null,
                'order' => 999,
                'place' => 0,
                'price' => 0.00,
                'date' => null,
                'created_at' => null,
                'updated_at' => null,
                'link' => null,
                'icon' => null,
            ],
            [
                'id' => 34,
                'active' => 1,
                'name' => 'Blog',
                'image' => null,
                'type' => 'social_network',
                'categories' => null,
                'order' => 999,
                'place' => 0,
                'price' => 0.00,
                'date' => null,
                'created_at' => null,
                'updated_at' => null,
                'link' => null,
                'icon' => null,
            ],
            [
                'id' => 35,
                'active' => 1,
                'name' => 'Delicious',
                'image' => null,
                'type' => 'social_network',
                'categories' => null,
                'order' => 999,
                'place' => 0,
                'price' => 0.00,
                'date' => null,
                'created_at' => null,
                'updated_at' => null,
                'link' => null,
                'icon' => null,
            ],
            [
                'id' => 36,
                'active' => 1,
                'name' => 'Dribbble',
                'image' => null,
                'type' => 'social_network',
                'categories' => null,
                'order' => 999,
                'place' => 0,
                'price' => 0.00,
                'date' => null,
                'created_at' => null,
                'updated_at' => null,
                'link' => null,
                'icon' => null,
            ],
            [
                'id' => 37,
                'active' => 1,
                'name' => 'Facebook',
                'image' => null,
                'type' => 'social_network',
                'categories' => null,
                'order' => 999,
                'place' => 0,
                'price' => 0.00,
                'date' => null,
                'created_at' => null,
                'updated_at' => null,
                'link' => null,
                'icon' => null,
            ],
            [
                'id' => 38,
                'active' => 1,
                'name' => 'Flickr',
                'image' => null,
                'type' => 'social_network',
                'categories' => null,
                'order' => 999,
                'place' => 0,
                'price' => 0.00,
                'date' => null,
                'created_at' => null,
                'updated_at' => null,
                'link' => null,
                'icon' => null,
            ],
            [
                'id' => 39,
                'active' => 1,
                'name' => 'Google',
                'image' => null,
                'type' => 'social_network',
                'categories' => null,
                'order' => 999,
                'place' => 0,
                'price' => 0.00,
                'date' => null,
                'created_at' => null,
                'updated_at' => null,
                'link' => null,
                'icon' => null,
            ],
            [
                'id' => 40,
                'active' => 1,
                'name' => 'Instagram',
                'image' => null,
                'type' => 'social_network',
                'categories' => null,
                'order' => 999,
                'place' => 0,
                'price' => 0.00,
                'date' => null,
                'created_at' => null,
                'updated_at' => null,
                'link' => null,
                'icon' => null,
            ],
            [
                'id' => 41,
                'active' => 1,
                'name' => 'Linkedin',
                'image' => null,
                'type' => 'social_network',
                'categories' => null,
                'order' => 999,
                'place' => 0,
                'price' => 0.00,
                'date' => null,
                'created_at' => null,
                'updated_at' => null,
                'link' => null,
                'icon' => null,
            ],
            [
                'id' => 42,
                'active' => 1,
                'name' => 'Pinterest',
                'image' => null,
                'type' => 'social_network',
                'categories' => null,
                'order' => 999,
                'place' => 0,
                'price' => 0.00,
                'date' => null,
                'created_at' => null,
                'updated_at' => null,
                'link' => null,
                'icon' => null,
            ],
            [
                'id' => 43,
                'active' => 1,
                'name' => 'Rss',
                'image' => null,
                'type' => 'social_network',
                'categories' => null,
                'order' => 999,
                'place' => 0,
                'price' => 0.00,
                'date' => null,
                'created_at' => null,
                'updated_at' => null,
                'link' => null,
                'icon' => null,
            ],
            [
                'id' => 44,
                'active' => 1,
                'name' => 'Skype',
                'image' => null,
                'type' => 'social_network',
                'categories' => null,
                'order' => 999,
                'place' => 0,
                'price' => 0.00,
                'date' => null,
                'created_at' => null,
                'updated_at' => null,
                'link' => null,
                'icon' => null,
            ],
            [
                'id' => 45,
                'active' => 1,
                'name' => 'TikTok',
                'image' => null,
                'type' => 'social_network',
                'categories' => null,
                'order' => 999,
                'place' => 0,
                'price' => 0.00,
                'date' => null,
                'created_at' => null,
                'updated_at' => null,
                'link' => null,
                'icon' => null,
            ],
            [
                'id' => 46,
                'active' => 1,
                'name' => 'Twitter',
                'image' => null,
                'type' => 'social_network',
                'categories' => null,
                'order' => 999,
                'place' => 0,
                'price' => 0.00,
                'date' => null,
                'created_at' => null,
                'updated_at' => null,
                'link' => null,
                'icon' => null,
            ],
            [
                'id' => 47,
                'active' => 1,
                'name' => 'Vimeo',
                'image' => null,
                'type' => 'social_network',
                'categories' => null,
                'order' => 999,
                'place' => 0,
                'price' => 0.00,
                'date' => null,
                'created_at' => null,
                'updated_at' => null,
                'link' => null,
                'icon' => null,
            ],
            [
                'id' => 48,
                'active' => 1,
                'name' => 'Whatsapp',
                'image' => null,
                'type' => 'social_network',
                'categories' => null,
                'order' => 999,
                'place' => 0,
                'price' => 0.00,
                'date' => null,
                'created_at' => null,
                'updated_at' => null,
                'link' => null,
                'icon' => null,
            ],
            [
                'id' => 49,
                'active' => 1,
                'name' => 'Youtube',
                'image' => null,
                'type' => 'social_network',
                'categories' => null,
                'order' => 999,
                'place' => 0,
                'price' => 0.00,
                'date' => null,
                'created_at' => null,
                'updated_at' => null,
                'link' => null,
                'icon' => null,
            ],
            [
                'id' => 50,
                'active' => 1,
                'name' => 'Comercial',
                'image' => null,
                'type' => 'contact',
                'categories' => null,
                'order' => 999,
                'place' => 0,
                'price' => 0.00,
                'date' => null,
                'created_at' => null,
                'updated_at' => null,
                'link' => null,
                'icon' => null,
            ],
            [
                'id' => 51,
                'active' => 1,
                'name' => 'Financeiro',
                'image' => null,
                'type' => 'contact',
                'categories' => null,
                'order' => 999,
                'place' => 0,
                'price' => 0.00,
                'date' => null,
                'created_at' => null,
                'updated_at' => null,
                'link' => null,
                'icon' => null,
            ],
            [
                'id' => 52,
                'active' => 1,
                'name' => 'RH',
                'image' => null,
                'type' => 'contact',
                'categories' => null,
                'order' => 999,
                'place' => 0,
                'price' => 0.00,
                'date' => null,
                'created_at' => null,
                'updated_at' => null,
                'link' => null,
                'icon' => null,
            ]
        ]);
    }

    public function down()
    {
        DB::table('items')->truncate();
    }
}
