<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

class InsertXSettingsData extends Migration
{
    public function up()
    {
        DB::table('x_settings')->insert([
            [
                'id' => 1,
                'fields' => 'version',
                'value' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 2,
                'fields' => 'name_site',
                'value' => 'Site',
                'created_at' => null,
                'updated_at' => '2025-03-25 06:14:53',
            ],
            [
                'id' => 3,
                'fields' => 'meta_title',
                'value' => 'Site',
                'created_at' => null,
                'updated_at' => '2025-03-25 06:14:53',
            ],
            [
                'id' => 4,
                'fields' => 'meta_keywords',
                'value' => 'Site',
                'created_at' => null,
                'updated_at' => '2025-03-25 06:14:53',
            ],
            [
                'id' => 5,
                'fields' => 'meta_description',
                'value' => 'Site',
                'created_at' => null,
                'updated_at' => '2025-03-25 06:14:53',
            ],
            [
                'id' => 6,
                'fields' => 'image_favicon',
                'value' => '[]',
                'created_at' => null,
                'updated_at' => '2025-03-25 06:14:54',
            ],
            [
                'id' => 7,
                'fields' => 'image_sharing',
                'value' => '[]',
                'created_at' => null,
                'updated_at' => '2025-03-25 06:14:54',
            ],
            [
                'id' => 8,
                'fields' => 'image_sharing_mime',
                'value' => '',
                'created_at' => null,
                'updated_at' => '2025-03-25 06:14:54',
            ],
            [
                'id' => 9,
                'fields' => 'image_sharing_width',
                'value' => '',
                'created_at' => null,
                'updated_at' => '2025-03-25 06:14:54',
            ],
            [
                'id' => 10,
                'fields' => 'image_sharing_height',
                'value' => '',
                'created_at' => null,
                'updated_at' => '2025-03-25 06:14:54',
            ],
            [
                'id' => 11,
                'fields' => 'thumbs_jpg_to_webp',
                'value' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 12,
                'fields' => 'thumbs_jpg_to_jpg',
                'value' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 13,
                'fields' => 'thumbs_png_to_web',
                'value' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 14,
                'fields' => 'thumbs_png_to_jpg',
                'value' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 15,
                'fields' => 'thumbs_webp_to_webp',
                'value' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 16,
                'fields' => 'script',
                'value' => '',
                'created_at' => null,
                'updated_at' => '2025-04-08 19:34:00',
            ],
            [
                'id' => 17,
                'fields' => 'email',
                'value' => 'teste@hotmail.com',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 18,
                'fields' => 'cnpj',
                'value' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 19,
                'fields' => 'address',
                'value' => 'Rua Z',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 20,
                'fields' => 'opening_hours',
                'value' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 21,
                'fields' => 'email_1',
                'value' => 'teste@hotmail.com',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 22,
                'fields' => 'phone',
                'value' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 23,
                'fields' => 'whatsapp',
                'value' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 24,
                'fields' => 'whatsapp_code',
                'value' => 55,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 25,
                'fields' => 'whatsapp_text',
                'value' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 26,
                'fields' => 'key_google',
                'value' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 27,
                'fields' => 'key_captcha',
                'value' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 28,
                'fields' => 'shippings_correios',
                'value' => 0,
                'created_at' => '2025-03-01 07:59:39',
                'updated_at' => '2025-04-16 03:58:03',
            ],
            [
                'id' => 29,
                'fields' => 'shippings_correios_code_acess',
                'value' => '',
                'created_at' => '2025-03-01 07:59:39',
                'updated_at' => '2025-04-16 03:58:03',
            ],
            [
                'id' => 30,
                'fields' => 'shippings_correios_usuario',
                'value' => '',
                'created_at' => '2025-03-03 14:05:49',
                'updated_at' => '2025-04-16 03:58:03',
            ],
            [
                'id' => 31,
                'fields' => 'shippings_correios_contrato',
                'value' => '',
                'created_at' => '2025-03-03 14:05:49',
                'updated_at' => '2025-04-16 03:58:03',
            ],
            [
                'id' => 32,
                'fields' => 'shippings_correios_dr',
                'value' => '',
                'created_at' => '2025-03-03 14:05:49',
                'updated_at' => '2025-04-16 03:58:03',
            ],
            [
                'id' => 33,
                'fields' => 'shippings_correios_token',
                'value' => '',
                'created_at' => null,
                'updated_at' => '2025-04-01 08:28:45',
            ],
            [
                'id' => 34,
                'fields' => 'shippings_correios_token_expiration',
                'value' => '',
                'created_at' => null,
                'updated_at' => '2025-04-01 08:28:45',
            ],
            [
                'id' => 35,
                'fields' => 'shippings_correios_cartao_postagem',
                'value' => '',
                'created_at' => null,
                'updated_at' => '2025-04-16 03:58:03',
            ],
            [
                'id' => 36,
                'fields' => 'shippings_melhor_envio',
                'value' => 0,
                'created_at' => null,
                'updated_at' => '2025-04-16 03:58:03',
            ],
            [
                'id' => 37,
                'fields' => 'shippings_local',
                'value' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 38,
                'fields' => 'shippings_raio',
                'value' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 39,
                'fields' => 'shippings_moto_boy',
                'value' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 40,
                'fields' => 'shippings_retirar_na_loja',
                'value' => 0,
                'created_at' => null,
                'updated_at' => '2025-04-16 03:58:03',
            ],
            [
                'id' => 41,
                'fields' => 'shippings_price_moto_boy',
                'value' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 42,
                'fields' => 'shippings_melhor_envio_token',
                'value' => '',
                'created_at' => null,
                'updated_at' => '2025-04-16 03:58:03',
            ],
            [
                'id' => 43,
                'fields' => 'shippings_raio_lat',
                'value' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 44,
                'fields' => 'shippings_raio_lng',
                'value' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 45,
                'fields' => 'shippings_zipcode',
                'value' => '13.092-110',
                'created_at' => null,
                'updated_at' => '2025-04-16 03:58:03',
            ],
            [
                'id' => 46,
                'fields' => 'pay_card_credit_1',
                'value' => 'MercadoPago',
                'created_at' => null,
                'updated_at' => '2025-03-22 07:01:56',
            ],
            [
                'id' => 47,
                'fields' => 'pay_card_credit_2',
                'value' => 'AppMax',
                'created_at' => null,
                'updated_at' => '2025-03-22 07:01:56',
            ],
            [
                'id' => 48,
                'fields' => 'pay_card_credit_3',
                'value' => 0,
                'created_at' => null,
                'updated_at' => '2025-02-18 17:50:57',
            ],
            [
                'id' => 49,
                'fields' => 'pay_boleto_1',
                'value' => 'MercadoPago',
                'created_at' => null,
                'updated_at' => '2025-03-22 07:01:56',
            ],
            [
                'id' => 50,
                'fields' => 'pay_boleto_2',
                'value' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 51,
                'fields' => 'pay_boleto_3',
                'value' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 52,
                'fields' => 'pay_pix_1',
                'value' => 'MercadoPago',
                'created_at' => null,
                'updated_at' => '2025-03-22 07:01:56',
            ],
            [
                'id' => 53,
                'fields' => 'pay_pix_2',
                'value' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 54,
                'fields' => 'pay_pix_3',
                'value' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 55,
                'fields' => 'pay_boleto_days_expire',
                'value' => 3,
                'created_at' => null,
                'updated_at' => '2025-03-22 07:01:56',
            ],
            [
                'id' => 56,
                'fields' => 'pay_card_credit_installments_max',
                'value' => 12,
                'created_at' => null,
                'updated_at' => '2025-03-22 07:01:56',
            ],
            [
                'id' => 57,
                'fields' => 'pay_card_credit_installments_fees',
                'value' => 6,
                'created_at' => null,
                'updated_at' => '2025-03-22 07:01:56',
            ],
            [
                'id' => 58,
                'fields' => 'pay_card_credit_installments_interest_perc',
                'value' => 1.00,
                'created_at' => null,
                'updated_at' => '2025-03-22 07:01:56',
            ],
            [
                'id' => 59,
                'fields' => 'pay_rates_card_credit',
                'value' => 0.00,
                'created_at' => null,
                'updated_at' => '2025-03-22 07:01:56',
            ],
            [
                'id' => 60,
                'fields' => 'pay_rates_boleto',
                'value' => 0.00,
                'created_at' => null,
                'updated_at' => '2025-03-22 07:01:56',
            ],
            [
                'id' => 61,
                'fields' => 'pay_rates_pix',
                'value' => 0.00,
                'created_at' => null,
                'updated_at' => '2025-03-22 07:01:56',
            ],
            [
                'id' => 62,
                'fields' => 'pay_discount_card_credit',
                'value' => 0.00,
                'created_at' => null,
                'updated_at' => '2025-03-22 07:01:56',
            ],
            [
                'id' => 63,
                'fields' => 'pay__discount_boleto',
                'value' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 64,
                'fields' => 'pay__discount_pix',
                'value' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 65,
                'fields' => 'pay_discount_boleto',
                'value' => 0.00,
                'created_at' => '2024-12-14 17:44:58',
                'updated_at' => '2025-03-22 07:01:56',
            ],
            [
                'id' => 66,
                'fields' => 'pay_discount_pix',
                'value' => 0.00,
                'created_at' => '2024-12-14 17:44:58',
                'updated_at' => '2025-03-22 07:01:56',
            ],
            [
                'id' => 67,
                'fields' => 'pay_pagarme_client_id',
                'value' => '',
                'created_at' => null,
                'updated_at' => '2025-02-18 17:52:51',
            ],
            [
                'id' => 68,
                'fields' => 'pay_pagarme_client_secret',
                'value' => '',
                'created_at' => null,
                'updated_at' => '2025-02-18 17:52:51',
            ],
            [
                'id' => 69,
                'fields' => 'pay_pagseguro_token',
                'value' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 70,
                'fields' => 'pay_pagseguro_environment',
                'value' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 71,
                'fields' => 'pay_pagseguro_public_key',
                'value' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 72,
                'fields' => 'pay_mercado_pago_public_key',
                'value' => '',
                'created_at' => null,
                'updated_at' => '2025-03-22 07:01:56',
            ],
            [
                'id' => 73,
                'fields' => 'pay_mercado_pago_access_token',
                'value' => '',
                'created_at' => null,
                'updated_at' => '2025-03-22 07:01:56',
            ],
            [
                'id' => 74,
                'fields' => 'pay_appmax_token',
                'value' => '',
                'created_at' => null,
                'updated_at' => '2025-03-22 07:01:56',
            ],
            [
                'id' => 75,
                'fields' => 'smtp_active',
                'value' => 0,
                'created_at' => null,
                'updated_at' => '2025-03-27 04:31:32',
            ],
            [
                'id' => 76,
                'fields' => 'smtp_ssl',
                'value' => 0,
                'created_at' => null,
                'updated_at' => '2025-03-27 04:31:32',
            ],
            [
                'id' => 77,
                'fields' => 'smtp_smtp',
                'value' => '',
                'created_at' => null,
                'updated_at' => '2025-03-27 04:31:32',
            ],
            [
                'id' => 78,
                'fields' => 'smtp_email',
                'value' => '',
                'created_at' => null,
                'updated_at' => '2025-03-27 04:31:32',
            ],
            [
                'id' => 79,
                'fields' => 'smtp_password',
                'value' => '',
                'created_at' => null,
                'updated_at' => '2025-03-27 04:31:32',
            ],
            [
                'id' => 80,
                'fields' => 'google_maps_zoom',
                'value' => 18,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 81,
                'fields' => 'google_maps_address',
                'value' => 'Av. Brasil 100 Bh Mg',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 82,
                'fields' => 'google_maps_lat',
                'value' => -19.9238381,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 83,
                'fields' => 'google_maps_lng',
                'value' => -43.9214651,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 84,
                'fields' => 'pg_login_name',
                'value' => 'Bem vindo <br>ao Tab info',
                'created_at' => '2025-09-08 23:42:11',
                'updated_at' => '2025-09-08 23:42:11',
            ],
            [
                'id' => 85,
                'fields' => 'pg_login_description',
                'value' => 'lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut laborelorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut laborelorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut laborelorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore',
                'created_at' => '2025-09-08 23:42:11',
                'updated_at' => '2025-09-08 23:42:11',
            ],
            [
                'id' => 86,
                'fields' => 'campanha_description',
                'value' => '',
                'created_at' => '2025-09-08 23:42:11',
                'updated_at' => '2025-09-08 23:42:11',
            ]
        ]);
    }

    public function down()
    {
        DB::table('x_settings')->truncate();
    }
}
