<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

class InsertYMenuAdminData extends Migration
{
    public function up()
    {
        DB::table('y_menu_admin')->insert([
            [
                'id' => 1,
                'active' => 1,
                'table__' => 'YMenuAdmin',
                'categories' => 100,
                'name' => 'Menu Admin',
                'icon' => null,
                'type' => 0,
                'type_items' => null,
                'filter' => null,
                'orderby' => null,
                'order' => 999,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 2,
                'active' => 0,
                'table__' => 'YMenuAdmin',
                'categories' => 5000,
                'name' => 'Menu Admin',
                'icon' => null,
                'type' => 0,
                'type_items' => null,
                'filter' => '$query->where(\'active\', 1)->where(\'id\', \'!=\', 1)->where(\'id\', \'!=\', 2);',
                'orderby' => 'order ASC,',
                'order' => 5000,
                'created_at' => null,
                'updated_at' => '2025-02-18 09:19:38',
            ],
            [
                'id' => 6,
                'active' => 1,
                'table__' => 'Users',
                'categories' => 1,
                'name' => 'Administradores',
                'icon' => null,
                'type' => 0,
                'type_items' => null,
                'filter' => '$query->where(\'users.id\', \'!=\', 1);',
                'orderby' => null,
                'order' => 1,
                'created_at' => null,
                'updated_at' => '2025-04-24 15:27:26',
            ],
            [
                'id' => 11,
                'active' => 1,
                'table__' => 'XSettings',
                'categories' => 2500,
                'name' => 'Informações',
                'icon' => 'faa-gear',
                'type' => 1,
                'type_items' => null,
                'filter' => null,
                'orderby' => null,
                'order' => 4070,
                'created_at' => null,
                'updated_at' => '2025-02-19 10:11:38',
            ],
            [
                'id' => 12,
                'active' => 0,
                'table__' => 'XSettings',
                'categories' => 2500,
                'name' => 'Informações Padrões',
                'icon' => 'faa-gear',
                'type' => 1,
                'type_items' => null,
                'filter' => null,
                'orderby' => null,
                'order' => 4000,
                'created_at' => null,
                'updated_at' => '2025-01-14 04:46:09',
            ],
            [
                'id' => 13,
                'active' => 0,
                'table__' => 'XSettings',
                'categories' => 2500,
                'name' => 'Informações Frete',
                'icon' => 'faa-truck',
                'type' => 1,
                'type_items' => null,
                'filter' => null,
                'orderby' => null,
                'order' => 4010,
                'created_at' => null,
                'updated_at' => '2025-09-08 23:48:50',
            ],
            [
                'id' => 14,
                'active' => 1,
                'table__' => 'XSettings',
                'categories' => 2500,
                'name' => 'Emails',
                'icon' => 'faa-envelope',
                'type' => 1,
                'type_items' => null,
                'filter' => null,
                'orderby' => null,
                'order' => 4060,
                'created_at' => null,
                'updated_at' => '2025-01-23 19:00:42',
            ],
            [
                'id' => 15,
                'active' => 0,
                'table__' => 'Texts',
                'categories' => 1500,
                'name' => 'Emails Personalizados',
                'icon' => 'faa-envelope|faa-envelope-o',
                'type' => 0,
                'type_items' => 'emails',
                'filter' => '$query->where(\'texts.active\', 1);',
                'orderby' => 'order ASC, id ASC, name_main DESC,',
                'order' => 2800,
                'created_at' => null,
                'updated_at' => '2025-09-08 23:50:36',
            ],
            [
                'id' => 16,
                'active' => 0,
                'table__' => 'Logs',
                'categories' => 2000,
                'name' => 'Formúlarios',
                'icon' => 'faa-table',
                'type' => 0,
                'type_items' => null,
                'filter' => null,
                'orderby' => null,
                'order' => 3000,
                'created_at' => null,
                'updated_at' => '2025-01-14 04:46:09',
            ],
            [
                'id' => 17,
                'active' => 1,
                'table__' => 'XSettings',
                'categories' => 2500,
                'name' => 'Config. do Site',
                'icon' => 'faa-gear',
                'type' => 1,
                'type_items' => null,
                'filter' => null,
                'orderby' => null,
                'order' => 4030,
                'created_at' => null,
                'updated_at' => '2025-09-08 23:48:54',
            ],
            [
                'id' => 18,
                'active' => 1,
                'table__' => 'XSettings',
                'categories' => 2500,
                'name' => 'Script',
                'icon' => 'faa-code',
                'type' => 1,
                'type_items' => null,
                'filter' => null,
                'orderby' => null,
                'order' => 4040,
                'created_at' => null,
                'updated_at' => '2025-01-15 01:46:09',
            ],
            [
                'id' => 19,
                'active' => 0,
                'table__' => 'XSettings',
                'categories' => 2500,
                'name' => 'Localização',
                'icon' => 'faa-globe',
                'type' => 1,
                'type_items' => null,
                'filter' => null,
                'orderby' => null,
                'order' => 4050,
                'created_at' => null,
                'updated_at' => '2025-01-14 04:46:09',
            ],
            [
                'id' => 26,
                'active' => 0,
                'table__' => 'Logs',
                'categories' => 2000,
                'name' => 'Login Clientes',
                'icon' => null,
                'type' => 0,
                'type_items' => null,
                'filter' => null,
                'orderby' => null,
                'order' => 3010,
                'created_at' => null,
                'updated_at' => '2025-01-14 07:46:09',
            ],
            [
                'id' => 27,
                'active' => 0,
                'table__' => 'Logs',
                'categories' => 3000,
                'name' => 'Login Admin',
                'icon' => null,
                'type' => 0,
                'type_items' => null,
                'filter' => null,
                'orderby' => null,
                'order' => 3015,
                'created_at' => null,
                'updated_at' => '2025-02-18 09:19:38',
            ],
            [
                'id' => 28,
                'active' => 0,
                'table__' => 'Logs',
                'categories' => 2000,
                'name' => 'Ações',
                'icon' => null,
                'type' => 0,
                'type_items' => null,
                'filter' => null,
                'orderby' => null,
                'order' => 3040,
                'created_at' => null,
                'updated_at' => '2025-01-14 04:46:09',
            ],
            [
                'id' => 31,
                'active' => 0,
                'table__' => 'Customers',
                'categories' => 200,
                'name' => 'Cadastro ALL',
                'icon' => null,
                'type' => 0,
                'type_items' => 'customers',
                'filter' => null,
                'orderby' => null,
                'order' => 200,
                'created_at' => null,
                'updated_at' => '2025-09-08 23:49:44',
            ],
            [
                'id' => 32,
                'active' => 0,
                'table__' => 'CustomersAddress',
                'categories' => 200,
                'name' => 'Endereços',
                'icon' => null,
                'type' => 0,
                'type_items' => null,
                'filter' => null,
                'orderby' => null,
                'order' => 250,
                'created_at' => null,
                'updated_at' => '2025-01-31 07:25:20',
            ],
            [
                'id' => 41,
                'active' => 0,
                'table__' => 'Products',
                'categories' => 500,
                'name' => 'Produtos',
                'icon' => 'faa-suitcase',
                'type' => 0,
                'type_items' => null,
                'filter' => null,
                'orderby' => null,
                'order' => 500,
                'created_at' => null,
                'updated_at' => '2025-09-08 23:50:33',
            ],
            [
                'id' => 42,
                'active' => 0,
                'table__' => 'ProductsCategories',
                'categories' => 500,
                'name' => 'Produtos (Categorias)',
                'icon' => 'faa-sitemap',
                'type' => 0,
                'type_items' => null,
                'filter' => '$query->where(\'type\', 0);',
                'orderby' => null,
                'order' => 501,
                'created_at' => null,
                'updated_at' => '2025-09-08 23:50:34',
            ],
            [
                'id' => 43,
                'active' => 0,
                'table__' => 'ProductsCategories',
                'categories' => 500,
                'name' => 'Produtos (Subcategorias)',
                'icon' => 'faa-sitemap',
                'type' => 0,
                'type_items' => null,
                'filter' => '$query->where(\'type\', \'!=\', 0);',
                'orderby' => null,
                'order' => 502,
                'created_at' => null,
                'updated_at' => '2025-01-14 04:46:09',
            ],
            [
                'id' => 44,
                'active' => 0,
                'table__' => 'ProductsBrands',
                'categories' => 500,
                'name' => 'Marcas',
                'icon' => null,
                'type' => 0,
                'type_items' => null,
                'filter' => null,
                'orderby' => null,
                'order' => 510,
                'created_at' => null,
                'updated_at' => '2025-09-08 23:50:34',
            ],
            [
                'id' => 53,
                'active' => 0,
                'table__' => 'Shippings',
                'categories' => 3500,
                'name' => 'Frete por Local----',
                'icon' => null,
                'type' => 0,
                'type_items' => null,
                'filter' => null,
                'orderby' => null,
                'order' => 3500,
                'created_at' => null,
                'updated_at' => '2025-02-18 09:19:38',
            ],
            [
                'id' => 54,
                'active' => 0,
                'table__' => 'Shippings',
                'categories' => 3500,
                'name' => 'Frete por Raio----',
                'icon' => null,
                'type' => 0,
                'type_items' => null,
                'filter' => null,
                'orderby' => null,
                'order' => 3510,
                'created_at' => null,
                'updated_at' => '2025-02-18 09:19:39',
            ],
            [
                'id' => 61,
                'active' => 0,
                'table__' => 'Orders',
                'categories' => 400,
                'name' => 'Pedidos',
                'icon' => null,
                'type' => 0,
                'type_items' => null,
                'filter' => null,
                'orderby' => 'id DESC,',
                'order' => 400,
                'created_at' => null,
                'updated_at' => '2025-09-08 23:50:32',
            ],
            [
                'id' => 62,
                'active' => 0,
                'table__' => 'OrdersStatus',
                'categories' => 400,
                'name' => 'Pedidos (Status)',
                'icon' => null,
                'type' => 0,
                'type_items' => null,
                'filter' => null,
                'orderby' => 'order ASC',
                'order' => 402,
                'created_at' => null,
                'updated_at' => '2025-09-08 23:50:33',
            ],
            [
                'id' => 63,
                'active' => 0,
                'table__' => 'OrdersEvents',
                'categories' => 2500,
                'name' => 'Cupons',
                'icon' => 'faa-ticket',
                'type' => 1,
                'type_items' => 'coupons',
                'filter' => null,
                'orderby' => null,
                'order' => 405,
                'created_at' => null,
                'updated_at' => '2025-01-14 22:46:09',
            ],
            [
                'id' => 67,
                'active' => 0,
                'table__' => 'XSettings',
                'categories' => 4000,
                'name' => 'Pagamentos',
                'icon' => 'faa-gear',
                'type' => 1,
                'type_items' => null,
                'filter' => null,
                'orderby' => null,
                'order' => 4020,
                'created_at' => null,
                'updated_at' => '2025-09-08 23:48:51',
            ],
            [
                'id' => 72,
                'active' => 0,
                'table__' => 'products',
                'categories' => 1500,
                'name' => 'Produtos mais Comprados----',
                'icon' => null,
                'type' => 0,
                'type_items' => null,
                'filter' => null,
                'orderby' => null,
                'order' => 1500,
                'created_at' => null,
                'updated_at' => '2025-02-18 09:19:39',
            ],
            [
                'id' => 73,
                'active' => 0,
                'table__' => 'products',
                'categories' => 1500,
                'name' => 'Produtos mais Visualizados----',
                'icon' => null,
                'type' => 0,
                'type_items' => null,
                'filter' => null,
                'orderby' => null,
                'order' => 1501,
                'created_at' => null,
                'updated_at' => '2025-02-18 09:19:39',
            ],
            [
                'id' => 81,
                'active' => 0,
                'table__' => 'Items',
                'categories' => 800,
                'name' => 'Banners',
                'icon' => 'faa-tv (alias)',
                'type' => 0,
                'type_items' => 'banners',
                'filter' => null,
                'orderby' => null,
                'order' => 1000,
                'created_at' => null,
                'updated_at' => '2025-09-08 23:50:35',
            ],
            [
                'id' => 82,
                'active' => 0,
                'table__' => 'Items',
                'categories' => 800,
                'name' => 'Blog',
                'icon' => 'faa-newspaper-o',
                'type' => 0,
                'type_items' => 'blog',
                'filter' => null,
                'orderby' => null,
                'order' => 1030,
                'created_at' => null,
                'updated_at' => '2025-01-14 04:46:09',
            ],
            [
                'id' => 83,
                'active' => 0,
                'table__' => 'ItemsCategories',
                'categories' => 800,
                'name' => 'Blog (Categorias)',
                'icon' => 'faa-sitemap',
                'type' => 0,
                'type_items' => 'blog',
                'filter' => null,
                'orderby' => null,
                'order' => 1031,
                'created_at' => null,
                'updated_at' => '2025-01-14 04:46:09',
            ],
            [
                'id' => 85,
                'active' => 0,
                'table__' => 'Items',
                'categories' => 800,
                'name' => 'Rede Social',
                'icon' => null,
                'type' => 0,
                'type_items' => 'social_network',
                'filter' => null,
                'orderby' => null,
                'order' => 1050,
                'created_at' => null,
                'updated_at' => '2025-01-14 07:46:09',
            ],
            [
                'id' => 86,
                'active' => 0,
                'table__' => 'Items',
                'categories' => 800,
                'name' => 'Faq',
                'icon' => 'faa-external-link-square',
                'type' => 0,
                'type_items' => 'faq',
                'filter' => null,
                'orderby' => null,
                'order' => 1040,
                'created_at' => null,
                'updated_at' => '2025-01-14 04:46:09',
            ],
            [
                'id' => 87,
                'active' => 1,
                'table__' => 'XSettings',
                'categories' => 2000,
                'name' => 'Textos / Imagens',
                'icon' => 'faa-file-text|faa-file-text-o',
                'type' => 1,
                'type_items' => null,
                'filter' => '$query->where(\'id\', 11);',
                'orderby' => null,
                'order' => 2010,
                'created_at' => null,
                'updated_at' => '2025-02-17 19:27:25',
            ],
            [
                'id' => 88,
                'active' => 0,
                'table__' => 'Texts',
                'categories' => 1500,
                'name' => 'Paginas',
                'icon' => 'faa-file-text|faa-file-text-o',
                'type' => 0,
                'type_items' => 'text',
                'filter' => '$query->where(\'texts.active\', 1);',
                'orderby' => null,
                'order' => 1710,
                'created_at' => null,
                'updated_at' => '2025-09-08 23:50:36',
            ],
            [
                'id' => 89,
                'active' => 0,
                'table__' => 'Items',
                'categories' => 800,
                'name' => 'Assuntos (Pag. Contato)',
                'icon' => 'faa-envelope-o',
                'type' => 0,
                'type_items' => 'contact',
                'filter' => null,
                'orderby' => null,
                'order' => 1070,
                'created_at' => null,
                'updated_at' => '2025-01-14 04:46:09',
            ],
            [
                'id' => 90,
                'active' => 0,
                'table__' => 'Newsletter',
                'categories' => 800,
                'name' => 'Newsletter',
                'icon' => 'faa-newspaper-o',
                'type' => 0,
                'type_items' => null,
                'filter' => null,
                'orderby' => null,
                'order' => 1060,
                'created_at' => null,
                'updated_at' => '2025-01-14 04:46:09',
            ],
            [
                'id' => 91,
                'active' => 0,
                'table__' => 'Items',
                'categories' => 800,
                'name' => 'Chamada Home',
                'icon' => null,
                'type' => 0,
                'type_items' => 'home_call',
                'filter' => null,
                'orderby' => null,
                'order' => 1020,
                'created_at' => null,
                'updated_at' => '2025-01-14 04:46:09',
            ],
            [
                'id' => 1001,
                'active' => 1,
                'table__' => 'Customers',
                'categories' => 200,
                'name' => 'Cadastro',
                'icon' => 'faa-user',
                'type' => 2,
                'type_items' => 'customers',
                'filter' => '$query->where(\'id\', \'!=\', $request->user()->id);',
                'orderby' => 'created_at DESC,',
                'order' => 200,
                'created_at' => '2025-09-08 23:49:42',
                'updated_at' => '2025-03-19 04:51:19',
            ],
            [
                'id' => 1002,
                'active' => 1,
                'table__' => 'Customers',
                'categories' => 200,
                'name' => 'Cadastro',
                'icon' => 'faa-user',
                'type' => 0,
                'type_items' => 'customers',
                'filter' => null,
                'orderby' => 'created_at DESC,',
                'order' => 200,
                'created_at' => '2025-09-08 23:49:42',
                'updated_at' => '2025-03-19 04:51:19',
            ],
            [
                'id' => 1003,
                'active' => 0,
                'table__' => 'CustomersAddress',
                'categories' => 200,
                'name' => 'Endereços',
                'icon' => null,
                'type' => 2,
                'type_items' => null,
                'filter' => '$query->where(\'customers\', $request->user()->id);',
                'orderby' => null,
                'order' => 250,
                'created_at' => '2025-09-09 00:09:50',
                'updated_at' => '2025-03-23 19:08:42',
            ]
        ]);
    }

    public function down()
    {
        DB::table('y_menu_admin')->truncate();
    }
}
