<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

class InsertYMenuAdminCategoriesData extends Migration
{
    public function up()
    {
        DB::table('y_menu_admin_categories')->insert([
            [
                'id' => 1,
                'active' => 1,
                'name' => '0001 - Administradores',
                'title' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 100,
                'active' => 1,
                'name' => 0100,
                'title' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 200,
                'active' => 1,
                'name' => '0200 - Cadastro',
                'title' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 300,
                'active' => 1,
                'name' => 0300,
                'title' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 400,
                'active' => 1,
                'name' => '0400 - Pedidos',
                'title' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 500,
                'active' => 1,
                'name' => '0500 - Produtos',
                'title' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 600,
                'active' => 1,
                'name' => 0600,
                'title' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 700,
                'active' => 1,
                'name' => 0700,
                'title' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 800,
                'active' => 1,
                'name' => '0800 - Geral',
                'title' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 900,
                'active' => 1,
                'name' => 0900,
                'title' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 1000,
                'active' => 1,
                'name' => '1000 - Site',
                'title' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 1100,
                'active' => 1,
                'name' => 1100,
                'title' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 1200,
                'active' => 1,
                'name' => 1200,
                'title' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 1300,
                'active' => 1,
                'name' => 1300,
                'title' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 1400,
                'active' => 1,
                'name' => 1400,
                'title' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 1500,
                'active' => 1,
                'name' => '1500 - Estatísticas',
                'title' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 1600,
                'active' => 1,
                'name' => 1600,
                'title' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 1700,
                'active' => 1,
                'name' => '1700 - Páginas',
                'title' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 1800,
                'active' => 1,
                'name' => 1800,
                'title' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 1900,
                'active' => 1,
                'name' => 1900,
                'title' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 2000,
                'active' => 1,
                'name' => '2000 - Textos',
                'title' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 2100,
                'active' => 1,
                'name' => 2100,
                'title' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 2200,
                'active' => 1,
                'name' => 2200,
                'title' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 2300,
                'active' => 1,
                'name' => 2300,
                'title' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 2400,
                'active' => 1,
                'name' => 2400,
                'title' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 2500,
                'active' => 1,
                'name' => '2500 - ',
                'title' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 2600,
                'active' => 1,
                'name' => 2600,
                'title' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 2700,
                'active' => 1,
                'name' => 2700,
                'title' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 2800,
                'active' => 1,
                'name' => '2800 - Emails',
                'title' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 2900,
                'active' => 1,
                'name' => 2900,
                'title' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 3000,
                'active' => 1,
                'name' => '3000 - Logs',
                'title' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 3100,
                'active' => 1,
                'name' => 3100,
                'title' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 3200,
                'active' => 1,
                'name' => 3200,
                'title' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 3300,
                'active' => 1,
                'name' => 3300,
                'title' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 3400,
                'active' => 1,
                'name' => 3400,
                'title' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 3500,
                'active' => 1,
                'name' => '3500 - Fretes',
                'title' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 3600,
                'active' => 1,
                'name' => 3600,
                'title' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 3700,
                'active' => 1,
                'name' => 3700,
                'title' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 3800,
                'active' => 1,
                'name' => 3800,
                'title' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 3900,
                'active' => 1,
                'name' => 3900,
                'title' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 4000,
                'active' => 1,
                'name' => '4000 - Configurações',
                'title' => 'Configurações',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 4100,
                'active' => 1,
                'name' => 4100,
                'title' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 4200,
                'active' => 1,
                'name' => 4200,
                'title' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 4300,
                'active' => 1,
                'name' => 4300,
                'title' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 4400,
                'active' => 1,
                'name' => 4400,
                'title' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 4500,
                'active' => 1,
                'name' => 4500,
                'title' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 4600,
                'active' => 1,
                'name' => 4600,
                'title' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 4700,
                'active' => 1,
                'name' => 4700,
                'title' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 4800,
                'active' => 1,
                'name' => 4800,
                'title' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 4900,
                'active' => 1,
                'name' => 4900,
                'title' => '',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 5000,
                'active' => 1,
                'name' => '5000 - Menu Admin',
                'title' => '',
                'created_at' => null,
                'updated_at' => null,
            ]
        ]);
    }

    public function down()
    {
        DB::table('y_menu_admin_categories')->truncate();
    }
}
